name: Generate Changelog
on:
  release:
    types: [published]
    branches: [master]
permissions:
  contents: write
jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate Changelog
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Put changelot to env
        id: generate_changelog
        run: |
          {
            echo 'CHANGELOG<<EOF'
            cat CHANGELOG.md
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Add changelog to release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.release.id }}
          body: |
            ${{ steps.generate_changelog.outputs.generate_changelog.CHANGELOG }}
